name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4

      # Устанавливаем JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Настройка Gradle (опционально, для кэширования и оптимизации)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Делаем gradlew исполняемым (важно для Linux runner)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Собираем проект
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # Прогоняем тесты
      - name: Run tests
        run: ./gradlew test
